# Generated by Django 3.2.13 on 2022-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
